spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    # ??
    #    url: jdbc:mysql://localhost:3306/todotest?serverTimezone=UTC&characterEncoding=UTF-8
    #    username: root
    #    password: a123

    # RDS
    url: jdbc:mysql://sidequestdb.cinzzb9ewscr.ap-northeast-2.rds.amazonaws.com:3306/todotest?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: admin
    password: a123789456
  jpa:
    hibernate:
      ddl-auto: update